// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

//go:generate go run github.com/kilianpaquier/go-builder-generator/cmd/go-builder-generator@latest generate -d . -f ../types.go -s Export

package builders

import (
	"github.com/kilianpaquier/go-builder-generator/testdata/success_export"
)

// ExportBuilder represents Export's builder.
type ExportBuilder struct {
	build success_export.Export
}

// NewExportBuilder creates a new ExportBuilder.
func NewExportBuilder() *ExportBuilder {
	return &ExportBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *ExportBuilder) Copy() *ExportBuilder {
	return &ExportBuilder{b.build}
}

// Build returns built Export.
func (b *ExportBuilder) Build() *success_export.Export {
	result := b.build
	return &result
}

// Int64Alias sets Export's Int64Alias.
func (b *ExportBuilder) Int64Alias(int64Alias success_export.Int64Alias) *ExportBuilder {
	b.build.Int64Alias = int64Alias
	return b
}
