// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

// Code generated from types.go.

package naming

import "github.com/kilianpaquier/go-builder-generator/testdata/success_package/naming/another_folder/naming"

// NamingBuilder represents Naming's builder.
type NamingBuilder struct {
	build Naming
}

// NewNamingBuilder creates a new NamingBuilder.
func NewNamingBuilder() *NamingBuilder {
	return &NamingBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *NamingBuilder) Copy() *NamingBuilder {
	return &NamingBuilder{b.build}
}

// Build returns built Naming.
func (b *NamingBuilder) Build() *Naming {
	result := b.build
	return &result
}

// Field2 sets Naming's field2.
func (b *NamingBuilder) Field2(field2 naming.AnotherNaming) *NamingBuilder {
	b = b.Copy()
	b.build.field2 = field2
	return b
}
