// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package builders

import (
	"github.com/kilianpaquier/go-builder-generator/testdata/success_return_copy"
)

// ReturnCopyBuilder represents ReturnCopy's builder.
type ReturnCopyBuilder struct {
	build success_return_copy.ReturnCopy
}

// NewReturnCopyBuilder creates a new ReturnCopyBuilder.
func NewReturnCopyBuilder() *ReturnCopyBuilder {
	return &ReturnCopyBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *ReturnCopyBuilder) Copy() *ReturnCopyBuilder {
	return &ReturnCopyBuilder{b.build}
}

// Build returns built ReturnCopy.
func (b *ReturnCopyBuilder) Build() *success_return_copy.ReturnCopy {
	result := b.build
	return &result
}

// Field sets ReturnCopy's Field.
func (b *ReturnCopyBuilder) Field(field string) *ReturnCopyBuilder {
	b = b.Copy()
	b.build.Field = field
	return b
}

// Slice sets ReturnCopy's Slice.
func (b *ReturnCopyBuilder) Slice(slice ...string) *ReturnCopyBuilder {
	b = b.Copy()
	b.build.Slice = append(b.build.Slice, slice...)
	return b
}
