// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package builders

import (
	"reflect"

	"github.com/go-playground/validator/v10"
)

// InvalidValidationErrorBuilder represents InvalidValidationError's builder.
type InvalidValidationErrorBuilder struct {
	build validator.InvalidValidationError
}

// NewInvalidValidationErrorBuilder creates a new InvalidValidationErrorBuilder.
func NewInvalidValidationErrorBuilder() *InvalidValidationErrorBuilder {
	return &InvalidValidationErrorBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *InvalidValidationErrorBuilder) Copy() *InvalidValidationErrorBuilder {
	return &InvalidValidationErrorBuilder{b.build}
}

// Build returns built InvalidValidationError.
func (b *InvalidValidationErrorBuilder) Build() *validator.InvalidValidationError {
	result := b.build
	return &result
}

// Type sets InvalidValidationError's Type.
func (b *InvalidValidationErrorBuilder) Type(t reflect.Type) *InvalidValidationErrorBuilder {
	b.build.Type = t
	return b
}
