// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package builders

import (
	"context"

	"github.com/kilianpaquier/go-builder-generator/testdata/success_struct"
)

// StructBuilder represents Struct's builder.
type StructBuilder struct {
	build success_struct.Struct
}

// NewStructBuilder creates a new StructBuilder.
func NewStructBuilder() *StructBuilder {
	return &StructBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *StructBuilder) Copy() *StructBuilder {
	return &StructBuilder{b.build}
}

// Build returns built Struct.
func (b *StructBuilder) Build() *success_struct.Struct {
	result := b.build
	return &result
}

// AnotherStruct sets Struct's AnotherStruct.
func (b *StructBuilder) AnotherStruct(anotherStruct struct {
	Nested struct {
		Field string `json:"field,omitempty"`
		Ctx   context.Context
	}
	NotNested int64 `json:"not_nested"`
	Ctx       context.Context
	Alias     success_struct.Int64Alias
}) *StructBuilder {
	b.build.AnotherStruct = anotherStruct
	return b
}
