// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package builders

import (
	"github.com/kilianpaquier/go-builder-generator/testdata/success_struct"
)

// StructNoFieldsBuilder is an alias of StructNoFields to build StructNoFields with builder-pattern.
type StructNoFieldsBuilder success_struct.StructNoFields

// NewStructNoFieldsBuilder creates a new StructNoFieldsBuilder.
func NewStructNoFieldsBuilder() *StructNoFieldsBuilder {
	return &StructNoFieldsBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *StructNoFieldsBuilder) Copy() *StructNoFieldsBuilder {
	c := *b
	return &c
}

// Build returns built StructNoFields.
func (b *StructNoFieldsBuilder) Build() *success_struct.StructNoFields {
	return (*success_struct.StructNoFields)(b)
}

// SetNoFields sets StructNoFields's NoFields.
func (b *StructNoFieldsBuilder) SetNoFields(noFields struct{}) *StructNoFieldsBuilder {
	b.NoFields = noFields
	return b
}
