// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

//go:generate go run github.com/kilianpaquier/go-builder-generator/cmd/go-builder-generator@latest generate -d . -f ../types.go -s StructNoFields

package builders

import (
	"github.com/kilianpaquier/go-builder-generator/testdata/success_struct"
)

// StructNoFieldsBuilder represents StructNoFields's builder.
type StructNoFieldsBuilder struct {
	build success_struct.StructNoFields
}

// NewStructNoFieldsBuilder creates a new StructNoFieldsBuilder.
func NewStructNoFieldsBuilder() *StructNoFieldsBuilder {
	return &StructNoFieldsBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *StructNoFieldsBuilder) Copy() *StructNoFieldsBuilder {
	return &StructNoFieldsBuilder{b.build}
}

// Build returns built StructNoFields.
func (b *StructNoFieldsBuilder) Build() *success_struct.StructNoFields {
	result := b.build
	return &result
}

// NoFields sets StructNoFields's NoFields.
func (b *StructNoFieldsBuilder) NoFields(noFields struct{}) *StructNoFieldsBuilder {
	b.build.NoFields = noFields
	return b
}
