# Kickr configuration file (https://github.com/kickr-dev/kickr)
# yaml-language-server: $schema=https://raw.githubusercontent.com/kickr-dev/kickr/beta/.schemas/kickr.v1.schema.json
version: 1
github:
  options:
    - codecov
    - codeql
    - harden-runner
    - kickr:github-app
    - ossf-scorecard
    - renovate:personal-token
  release:
    auth: github-token
    auto: true
license: mit
maintainers:
  - name: kilianpaquier
platform: github
pre-commit:
  - conventional-commits
