# Kickr configuration file (https://github.com/kickr-dev/kickr)
# yaml-language-server: $schema=https://raw.githubusercontent.com/kickr-dev/kickr/beta/.schemas/kickr.v1.schema.json
version: 1
exclude:
  - shell
gitlab:
  options:
    - kickr
  release: {}
license: mit
maintainers:
  - name: kilianpaquier
platform: gitlab
pre-commit:
  - conventional-commits
