# Code generated by kickr; DO NOT EDIT.

include ./scripts/mk/*.mk

.DEFAULT_GOAL := help

.PHONY: help
help: ## list available targets.
	@grep -hE '^[a-zA-Z0-9_%-]+:' $(MAKEFILE_LIST) | sort -u | awk -F': ?' '{n = split($$0, a, "## "); printf "%-20s %s\n", $$1, (n > 1 ? a[2] : "")}'
