// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

// Code generated from types.go.

package builders

import (
	builded "github.com/kilianpaquier/go-builder-generator/testdata/local_dir"
	"github.com/kilianpaquier/go-builder-generator/testdata/local_dir/dir/local_dir"
)

// LocalImportBuilder represents LocalImport's builder.
type LocalImportBuilder struct {
	build builded.LocalImport
}

// NewLocalImportBuilder creates a new LocalImportBuilder.
func NewLocalImportBuilder() *LocalImportBuilder {
	return &LocalImportBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *LocalImportBuilder) Copy() *LocalImportBuilder {
	return &LocalImportBuilder{b.build}
}

// Build returns built LocalImport.
func (b *LocalImportBuilder) Build() *builded.LocalImport {
	result := b.build
	return &result
}

// Field2 sets LocalImport's Field2.
func (b *LocalImportBuilder) Field2(field2 local_dir.AnotherNaming) *LocalImportBuilder {
	b.build.Field2 = field2
	return b
}
