// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

// Code generated from success_same_package/result/types.go.

package success_same_package

import "context"

// unexportedTypeBuilder represents unexportedType's builder.
type unexportedTypeBuilder struct {
	build unexportedType
}

// newUnexportedTypeBuilder creates a new unexportedTypeBuilder.
func newUnexportedTypeBuilder() *unexportedTypeBuilder {
	return &unexportedTypeBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *unexportedTypeBuilder) Copy() *unexportedTypeBuilder {
	return &unexportedTypeBuilder{b.build}
}

// Build returns built unexportedType.
func (b *unexportedTypeBuilder) Build() *unexportedType {
	result := b.build
	return &result
}

// Ctx sets unexportedType's Ctx.
func (b *unexportedTypeBuilder) Ctx(ctx context.Context) *unexportedTypeBuilder {
	b.build.Ctx = ctx
	return b
}

// Int64Alias sets unexportedType's Int64Alias.
func (b *unexportedTypeBuilder) Int64Alias(int64Alias Int64Alias) *unexportedTypeBuilder {
	b.build.Int64Alias = int64Alias
	return b
}

// NonExported sets unexportedType's nonExported.
func (b *unexportedTypeBuilder) NonExported(nonExported string) *unexportedTypeBuilder {
	b.build.nonExported = nonExported
	return b
}

// NonExportedExportOpt sets unexportedType's nonExportedExportOpt.
func (b *unexportedTypeBuilder) NonExportedExportOpt(nonExportedExportOpt string) *unexportedTypeBuilder {
	b.build.nonExportedExportOpt = nonExportedExportOpt
	return b
}

// Primitive sets unexportedType's Primitive.
func (b *unexportedTypeBuilder) Primitive(primitive string) *unexportedTypeBuilder {
	b.build.Primitive = primitive
	return b
}
