// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

// Code generated from types.go.

package builders

import "github.com/kilianpaquier/go-builder-generator/testdata"

// UnionGenericBuilder represents UnionGeneric's builder.
type UnionGenericBuilder[T ~int | ~float64] struct {
	build testdata.UnionGeneric[T]
}

// NewUnionGenericBuilder creates a new UnionGenericBuilder.
func NewUnionGenericBuilder[T ~int | ~float64]() *UnionGenericBuilder[T] {
	return &UnionGenericBuilder[T]{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *UnionGenericBuilder[T]) Copy() *UnionGenericBuilder[T] {
	return &UnionGenericBuilder[T]{b.build}
}

// Build returns built UnionGeneric.
func (b *UnionGenericBuilder[T]) Build() *testdata.UnionGeneric[T] {
	result := b.build
	return &result
}

// Value sets UnionGeneric's Value.
func (b *UnionGenericBuilder[T]) Value(value T) *UnionGenericBuilder[T] {
	b.build.Value = value
	return b
}
