// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

// Code generated from types.go.

package builders

import "github.com/kilianpaquier/go-builder-generator/testdata"

// ExportBuilder represents Export's builder.
type ExportBuilder struct {
	build testdata.Export
}

// NewExportBuilder creates a new ExportBuilder.
func NewExportBuilder() *ExportBuilder {
	return &ExportBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *ExportBuilder) Copy() *ExportBuilder {
	return &ExportBuilder{b.build}
}

// Build returns built Export.
func (b *ExportBuilder) Build() *testdata.Export {
	result := b.build
	return &result
}

// Int64Alias sets Export's Int64Alias.
func (b *ExportBuilder) Int64Alias(int64Alias testdata.Int64Alias) *ExportBuilder {
	b.build.Int64Alias = int64Alias
	return b
}
