package cobra

import (
	"os"

	"github.com/spf13/cobra"

	"github.com/kilianpaquier/go-builder-generator/internal/generate"
)

func generateCmd() *cobra.Command {
	opts := generate.CLIOptions{}

	cmd := &cobra.Command{
		Use:   "generate",
		Short: "Generate builders for structs arguments present in file argument.",
		RunE: func(cmd *cobra.Command, _ []string) error {
			return generate.Run(cmd.Context(), opts, os.Args[2:]) // remove 'go-builder-generator generate' args
		},
	}

	// dest flag
	cmd.Flags().StringVarP(&opts.Destdir, "dest", "d", ".", "destination directory for the generated files")

	// files flag
	cmd.Flags().StringVarP(&opts.File, "file", "f", "", "input file containing golang struct(s) to generate builders on")
	_ = cmd.MarkFlagRequired("file")

	// no cmd flag
	cmd.Flags().BoolVar(&opts.NoCMD, "no-cmd", false, "removes top comment 'go:generate ...' from generated files")

	// no notice flag
	cmd.Flags().BoolVar(&opts.NoNotice, "no-notice", false, "removes top notice 'Code generated by ...' from generated files")

	// no tool flag
	cmd.Flags().BoolVar(&opts.NoTool, "no-tool", false, "avoid using go-build-generator as go tool when 'go:generate ...' is added in generated files")

	// specific package name flag
	cmd.Flags().StringVar(&opts.PackageName, "package-name", "",
		"defines a specific package name instead of '--dest', '-d' directory name. Only available when generating files in another directory")

	// setter prefix flag
	cmd.Flags().StringVarP(&opts.Prefix, "prefix", "p", "", "specific prefix to apply on setter functions")

	// copy before update and return copy
	cmd.Flags().BoolVar(&opts.ReturnCopy, "return-copy", false,
		"returns a copy of the builder each time a setter function is called")

	// structs flag
	cmd.Flags().StringSliceVarP(&opts.Structs, "structs", "s", []string{},
		"struct names to generate builders on (they must be contained in given input file). Multiple elements may be given by separating them with a comma or by providing multiple times the flag.")
	_ = cmd.MarkFlagRequired("structs")

	// validate func flag
	cmd.Flags().StringVar(&opts.ValidateFunc, "validate-func", "",
		"validate function name to be executed in Build, must have the signature 'func () error' and associated to built struct")

	return cmd
}
