// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

// Code generated from types.go.

package builders

import "github.com/kilianpaquier/go-builder-generator/testdata"

//go:generate go tool go-builder-generator generate -d . -f ../types.go -s SimpleTypeTool

// SimpleTypeToolBuilder represents SimpleTypeTool's builder.
type SimpleTypeToolBuilder struct {
	build testdata.SimpleTypeTool
}

// NewSimpleTypeToolBuilder creates a new SimpleTypeToolBuilder.
func NewSimpleTypeToolBuilder() *SimpleTypeToolBuilder {
	return &SimpleTypeToolBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *SimpleTypeToolBuilder) Copy() *SimpleTypeToolBuilder {
	return &SimpleTypeToolBuilder{b.build}
}

// Build returns built SimpleTypeTool.
func (b *SimpleTypeToolBuilder) Build() *testdata.SimpleTypeTool {
	result := b.build
	return &result
}

// Field sets SimpleTypeTool's Field.
func (b *SimpleTypeToolBuilder) Field(field int64) *SimpleTypeToolBuilder {
	b.build.Field = field
	return b
}
