// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package builders

import (
	"github.com/sirupsen/logrus"
	"github.com/sirupsen/logrus/hooks/test"
)

// HookBuilder represents Hook's builder.
type HookBuilder struct {
	build test.Hook
}

// NewHookBuilder creates a new HookBuilder.
func NewHookBuilder() *HookBuilder {
	return &HookBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *HookBuilder) Copy() *HookBuilder {
	return &HookBuilder{b.build}
}

// Build returns built Hook.
func (b *HookBuilder) Build() *test.Hook {
	result := b.build
	return &result
}

// Entries sets Hook's Entries.
func (b *HookBuilder) Entries(entries []logrus.Entry) *HookBuilder {
	b.build.Entries = entries
	return b
}
