// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package builders

import "github.com/stretchr/testify/mock"

// MockBuilder represents Mock's builder.
type MockBuilder struct {
	build mock.Mock
}

// NewMockBuilder creates a new MockBuilder.
func NewMockBuilder() *MockBuilder {
	return &MockBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *MockBuilder) Copy() *MockBuilder {
	return &MockBuilder{b.build}
}

// Build returns built Mock.
func (b *MockBuilder) Build() *mock.Mock {
	result := b.build
	return &result
}

// Calls sets Mock's Calls.
func (b *MockBuilder) Calls(calls []mock.Call) *MockBuilder {
	b.build.Calls = calls
	return b
}

// ExpectedCalls sets Mock's ExpectedCalls.
func (b *MockBuilder) ExpectedCalls(expectedCalls []*mock.Call) *MockBuilder {
	b.build.ExpectedCalls = expectedCalls
	return b
}
