// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

// Code generated from testdata/success_generic/types.go.

package builders

import "github.com/kilianpaquier/go-builder-generator/testdata/success_generic"

// SimpleGenericBuilder represents SimpleGeneric's builder.
type SimpleGenericBuilder[T any] struct {
	build success_generic.SimpleGeneric[T]
}

// NewSimpleGenericBuilder creates a new SimpleGenericBuilder.
func NewSimpleGenericBuilder[T any]() *SimpleGenericBuilder[T] {
	return &SimpleGenericBuilder[T]{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *SimpleGenericBuilder[T]) Copy() *SimpleGenericBuilder[T] {
	return &SimpleGenericBuilder[T]{b.build}
}

// Build returns built SimpleGeneric.
func (b *SimpleGenericBuilder[T]) Build() *success_generic.SimpleGeneric[T] {
	result := b.build
	return &result
}

// Value sets SimpleGeneric's Value.
func (b *SimpleGenericBuilder[T]) Value(value T) *SimpleGenericBuilder[T] {
	b.build.Value = value
	return b
}
