// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

// Code generated from testdata/success_interface/types.go

package builders

import (
	"context"

	"github.com/kilianpaquier/go-builder-generator/testdata/success_interface"
)

// InterfaceBuilder represents Interface's builder.
type InterfaceBuilder struct {
	build success_interface.Interface
}

// NewInterfaceBuilder creates a new InterfaceBuilder.
func NewInterfaceBuilder() *InterfaceBuilder {
	return &InterfaceBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *InterfaceBuilder) Copy() *InterfaceBuilder {
	return &InterfaceBuilder{b.build}
}

// Build returns built Interface.
func (b *InterfaceBuilder) Build() *success_interface.Interface {
	result := b.build
	return &result
}

// AnotherInterface sets Interface's AnotherInterface.
func (b *InterfaceBuilder) AnotherInterface(anotherInterface interface {
	SomeFunc() chan<- success_interface.Int64Alias
	SomeOtherFunc(ctx context.Context, c <-chan int64) error
	AFunc(i success_interface.Int64Alias) context.Context
}) *InterfaceBuilder {
	b.build.AnotherInterface = anotherInterface
	return b
}
