// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

// Code generated from types.go.

package builders

import "github.com/kilianpaquier/go-builder-generator/testdata"

// StructNoFieldsBuilder represents StructNoFields's builder.
type StructNoFieldsBuilder struct {
	build testdata.StructNoFields
}

// NewStructNoFieldsBuilder creates a new StructNoFieldsBuilder.
func NewStructNoFieldsBuilder() *StructNoFieldsBuilder {
	return &StructNoFieldsBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *StructNoFieldsBuilder) Copy() *StructNoFieldsBuilder {
	return &StructNoFieldsBuilder{b.build}
}

// Build returns built StructNoFields.
func (b *StructNoFieldsBuilder) Build() *testdata.StructNoFields {
	result := b.build
	return &result
}

// NoFields sets StructNoFields's NoFields.
func (b *StructNoFieldsBuilder) NoFields(noFields struct{}) *StructNoFieldsBuilder {
	b.build.NoFields = noFields
	return b
}
