// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

// Code generated from types.go.

package builders

import "github.com/kilianpaquier/go-builder-generator/testdata"

//go:generate go run github.com/kilianpaquier/go-builder-generator/cmd/go-builder-generator@latest generate -d . -f ../types.go -s SimpleTypeNoTool

// SimpleTypeNoToolBuilder represents SimpleTypeNoTool's builder.
type SimpleTypeNoToolBuilder struct {
	build testdata.SimpleTypeNoTool
}

// NewSimpleTypeNoToolBuilder creates a new SimpleTypeNoToolBuilder.
func NewSimpleTypeNoToolBuilder() *SimpleTypeNoToolBuilder {
	return &SimpleTypeNoToolBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *SimpleTypeNoToolBuilder) Copy() *SimpleTypeNoToolBuilder {
	return &SimpleTypeNoToolBuilder{b.build}
}

// Build returns built SimpleTypeNoTool.
func (b *SimpleTypeNoToolBuilder) Build() *testdata.SimpleTypeNoTool {
	result := b.build
	return &result
}

// Field sets SimpleTypeNoTool's Field.
func (b *SimpleTypeNoToolBuilder) Field(field int64) *SimpleTypeNoToolBuilder {
	b.build.Field = field
	return b
}
