// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

// Code generated from testdata/success_same_package_options/result/types.go.

package success_spo

import "context"

// unexportedTypeOptionsBuilder represents unexportedTypeOptions's builder.
type unexportedTypeOptionsBuilder struct {
	build unexportedTypeOptions
}

// newUnexportedTypeOptionsBuilder creates a new unexportedTypeOptionsBuilder.
func newUnexportedTypeOptionsBuilder() *unexportedTypeOptionsBuilder {
	return &unexportedTypeOptionsBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *unexportedTypeOptionsBuilder) Copy() *unexportedTypeOptionsBuilder {
	return &unexportedTypeOptionsBuilder{b.build}
}

// Build returns built unexportedTypeOptions.
func (b *unexportedTypeOptionsBuilder) Build() *unexportedTypeOptions {
	b = b.PrimitiveDef()

	result := b.build
	return &result
}

// SetCtx sets unexportedTypeOptions's Ctx.
func (b *unexportedTypeOptionsBuilder) SetCtx(ctx context.Context) *unexportedTypeOptionsBuilder {
	b.build.Ctx = ctx
	return b
}

// SetInt64Alias sets unexportedTypeOptions's Int64Alias.
func (b *unexportedTypeOptionsBuilder) SetInt64Alias(int64Alias Int64Alias) *unexportedTypeOptionsBuilder {
	b.build.Int64Alias = int64Alias
	return b
}

// SetNonExported sets unexportedTypeOptions's nonExported.
func (b *unexportedTypeOptionsBuilder) SetNonExported(nonExported string) *unexportedTypeOptionsBuilder {
	b.build.nonExported = nonExported
	return b
}

// SetNonExportedExportOpt sets unexportedTypeOptions's nonExportedExportOpt.
func (b *unexportedTypeOptionsBuilder) SetNonExportedExportOpt(nonExportedExportOpt string) *unexportedTypeOptionsBuilder {
	b.build.nonExportedExportOpt = nonExportedExportOpt
	return b
}

// SetPrimitive sets unexportedTypeOptions's Primitive.
func (b *unexportedTypeOptionsBuilder) SetPrimitive(primitive string) *unexportedTypeOptionsBuilder {
	b.build.Primitive = primitive
	return b
}
