// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

// Code generated from types.go.

package local

import "github.com/kilianpaquier/go-builder-generator/testdata/local/dir/local"

// LocalImportBuilder represents LocalImport's builder.
type LocalImportBuilder struct {
	build LocalImport
}

// NewLocalImportBuilder creates a new LocalImportBuilder.
func NewLocalImportBuilder() *LocalImportBuilder {
	return &LocalImportBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *LocalImportBuilder) Copy() *LocalImportBuilder {
	return &LocalImportBuilder{b.build}
}

// Build returns built LocalImport.
func (b *LocalImportBuilder) Build() *LocalImport {
	result := b.build
	return &result
}

// Exported sets LocalImport's Exported.
func (b *LocalImportBuilder) Exported(exported local.AnotherNaming) *LocalImportBuilder {
	b.build.Exported = exported
	return b
}

// unexported sets LocalImport's unexported.
func (b *LocalImportBuilder) unexported(unexported local.AnotherNaming) *LocalImportBuilder {
	b.build.unexported = unexported
	return b
}

// UnexportedTagged sets LocalImport's unexportedTagged.
func (b *LocalImportBuilder) UnexportedTagged(unexportedTagged local.AnotherNaming) *LocalImportBuilder {
	b.build.unexportedTagged = unexportedTagged
	return b
}
