// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package builders

import (
	"database/sql"
)

// NamedArgBuilder represents NamedArg's builder.
type NamedArgBuilder struct {
	build sql.NamedArg
}

// NewNamedArgBuilder creates a new NamedArgBuilder.
func NewNamedArgBuilder() *NamedArgBuilder {
	return &NamedArgBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *NamedArgBuilder) Copy() *NamedArgBuilder {
	return &NamedArgBuilder{b.build}
}

// Build returns built NamedArg.
func (b *NamedArgBuilder) Build() *sql.NamedArg {
	result := b.build
	return &result
}

// Name sets NamedArg's Name.
func (b *NamedArgBuilder) Name(name string) *NamedArgBuilder {
	b.build.Name = name
	return b
}

// Value sets NamedArg's Value.
func (b *NamedArgBuilder) Value(value any) *NamedArgBuilder {
	b.build.Value = value
	return b
}
