// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package builders

import (
	"os"
)

// SyscallErrorBuilder represents SyscallError's builder.
type SyscallErrorBuilder struct {
	build os.SyscallError
}

// NewSyscallErrorBuilder creates a new SyscallErrorBuilder.
func NewSyscallErrorBuilder() *SyscallErrorBuilder {
	return &SyscallErrorBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *SyscallErrorBuilder) Copy() *SyscallErrorBuilder {
	return &SyscallErrorBuilder{b.build}
}

// Build returns built SyscallError.
func (b *SyscallErrorBuilder) Build() *os.SyscallError {
	result := b.build
	return &result
}

// Err sets SyscallError's Err.
func (b *SyscallErrorBuilder) Err(err error) *SyscallErrorBuilder {
	b.build.Err = err
	return b
}

// Syscall sets SyscallError's Syscall.
func (b *SyscallErrorBuilder) Syscall(syscall string) *SyscallErrorBuilder {
	b.build.Syscall = syscall
	return b
}
