// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package builders

import (
	"github.com/kilianpaquier/go-builder-generator/root"
)

// RootTypeBuilder represents the builder of RootType to build RootType with builder-pattern.
type RootTypeBuilder struct {
	build root.RootType
}

// NewRootTypeBuilder creates a new RootTypeBuilder.
func NewRootTypeBuilder() *RootTypeBuilder {
	return &RootTypeBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *RootTypeBuilder) Copy() *RootTypeBuilder {
	return &RootTypeBuilder{b.build}
}

// Build returns built RootType.
func (b *RootTypeBuilder) Build() *root.RootType {
	result := &b.build
	return result
}

// Field sets RootType's Field.
func (b *RootTypeBuilder) Field(field int64) *RootTypeBuilder {
	b.build.Field = field
	return b
}
