// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

// Code generated from types.go.

package builders

import "github.com/kilianpaquier/go-builder-generator/testdata"

// InterfaceNoFieldsBuilder represents InterfaceNoFields's builder.
type InterfaceNoFieldsBuilder struct {
	build testdata.InterfaceNoFields
}

// NewInterfaceNoFieldsBuilder creates a new InterfaceNoFieldsBuilder.
func NewInterfaceNoFieldsBuilder() *InterfaceNoFieldsBuilder {
	return &InterfaceNoFieldsBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *InterfaceNoFieldsBuilder) Copy() *InterfaceNoFieldsBuilder {
	return &InterfaceNoFieldsBuilder{b.build}
}

// Build returns built InterfaceNoFields.
func (b *InterfaceNoFieldsBuilder) Build() *testdata.InterfaceNoFields {
	result := b.build
	return &result
}

// NoFields sets InterfaceNoFields's NoFields.
func (b *InterfaceNoFieldsBuilder) NoFields(noFields interface{}) *InterfaceNoFieldsBuilder {
	b.build.NoFields = noFields
	return b
}
