// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

// Code generated from types.go.

package builders

import (
	"context"

	"github.com/kilianpaquier/go-builder-generator/testdata"
)

// InterfaceBuilder represents Interface's builder.
type InterfaceBuilder struct {
	build testdata.Interface
}

// NewInterfaceBuilder creates a new InterfaceBuilder.
func NewInterfaceBuilder() *InterfaceBuilder {
	return &InterfaceBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *InterfaceBuilder) Copy() *InterfaceBuilder {
	return &InterfaceBuilder{b.build}
}

// Build returns built Interface.
func (b *InterfaceBuilder) Build() *testdata.Interface {
	result := b.build
	return &result
}

// AnotherInterface sets Interface's AnotherInterface.
func (b *InterfaceBuilder) AnotherInterface(anotherInterface interface {
	SomeFunc() chan<- testdata.Int64Alias
	SomeOtherFunc(ctx context.Context, c <-chan int64) error
	AFunc(i testdata.Int64Alias) context.Context
}) *InterfaceBuilder {
	b.build.AnotherInterface = anotherInterface
	return b
}

// InterfaceA sets Interface's InterfaceA.
func (b *InterfaceBuilder) InterfaceA(interfaceA interface {
	AFunc()
}) *InterfaceBuilder {
	b.build.InterfaceA = interfaceA
	return b
}

// InterfaceB sets Interface's InterfaceB.
func (b *InterfaceBuilder) InterfaceB(interfaceB interface {
	AFunc()
}) *InterfaceBuilder {
	b.build.InterfaceB = interfaceB
	return b
}
