// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

// Code generated from examples/no_dest/types.go.

package no_dest

// SomeStructBuilder represents SomeStruct's builder.
type SomeStructBuilder struct {
	build SomeStruct
}

// NewSomeStructBuilder creates a new SomeStructBuilder.
func NewSomeStructBuilder() *SomeStructBuilder {
	return &SomeStructBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *SomeStructBuilder) Copy() *SomeStructBuilder {
	return &SomeStructBuilder{b.build}
}

// Build returns built SomeStruct.
func (b *SomeStructBuilder) Build() *SomeStruct {
	result := b.build
	return &result
}

// SomeChan sets SomeStruct's SomeChan.
func (b *SomeStructBuilder) SomeChan(someChan chan<- SomeAlias) *SomeStructBuilder {
	b.build.SomeChan = someChan
	return b
}

// SomeSlice sets SomeStruct's SomeSlice.
func (b *SomeStructBuilder) SomeSlice(someSlice []string) *SomeStructBuilder {
	b.build.SomeSlice = someSlice
	return b
}
