# Code generated by craft; DO NOT EDIT.

GOCI_LINT_PATH  ?= .golangci.yml
VERSION         ?= v0.0.0

.PHONY: reports
reports:
	@mkdir -p reports/

.PHONY: lint
lint: reports
	@golangci-lint run -c ${GOCI_LINT_PATH} --timeout 240s --fast --sort-results \
		--out-format checkstyle:reports/go-ci-lint.checkstyle.xml,colored-line-number $(ARGS) || \
		echo "golangci-lint failed, running 'make lint-fix' may fix some issues"

.PHONY: lint-fix
lint-fix: reports
	@ARGS="--fix" make -s lint

.PHONY: test
test:
	@go test ./... -count 1 -timeout=15s

.PHONY: test-race
test-race:
	@CGO_ENABLED=1 go test ./... -race -timeout=15s

.PHONY: test-cover
test-cover: reports
	@go test ./... -coverpkg="./..." -covermode="count" -coverprofile="reports/go-coverage.native.out" -timeout=15s

.PHONY: build
build:
	@CGO_ENABLED=0 go build \
		-ldflags "\
			-X 'github.com/kilianpaquier/go-builder-generator/internal/build.branch=$(shell git rev-parse --abbrev-ref HEAD)' \
			-X 'github.com/kilianpaquier/go-builder-generator/internal/build.commit=$(shell git rev-parse HEAD)' \
			-X 'github.com/kilianpaquier/go-builder-generator/internal/build.date=$(shell TZ="UTC" date '+%Y-%m-%dT%TZ')' \
			-X 'github.com/kilianpaquier/go-builder-generator/internal/build.version=${VERSION}' \
		" \
		-o go-builder-generator ./cmd/go-builder-generator
