# Code generated by kickr; DO NOT EDIT.

.PHONY: clean
clean:
	@go clean
	@git clean -dfX

GOCI_LINT_PATH  ?= .golangci.yml
VERSION         ?= v0.0.0

.PHONY: lint
lint:
	@golangci-lint run --config=${GOCI_LINT_PATH} --timeout=240s --allow-parallel-runners \
		--output.text.path=stdout $(ARGS) || \
		echo "golangci-lint failed, running 'make lint-fix' may fix some issues"

.PHONY: lint-fix
lint-fix:
	@ARGS="--fix" make -s lint

.PHONY: test
test:
	@go test ./... -count 1 -timeout=30s

.PHONY: test-race
test-race:
	@CGO_ENABLED=1 go test ./... -race -timeout=30s

.PHONY: test-cover
test-cover:
	@go test ./... -v -coverpkg="./..." -covermode="count" -timeout=30s

.PHONY: build
build:
	@CGO_ENABLED=0 go build \
		-ldflags "\
			-X 'github.com/kilianpaquier/go-builder-generator/internal/build.branch=$(shell git rev-parse --abbrev-ref HEAD)' \
			-X 'github.com/kilianpaquier/go-builder-generator/internal/build.commit=$(shell git rev-parse HEAD)' \
			-X 'github.com/kilianpaquier/go-builder-generator/internal/build.date=$(shell TZ="UTC" date '+%Y-%m-%dT%TZ')' \
			-X 'github.com/kilianpaquier/go-builder-generator/internal/build.version=${VERSION}' \
		" \
		-o go-builder-generator ./cmd/go-builder-generator
