// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

// Code generated from pkg/types.go.

package builders

import (
	"unsafe"

	"github.com/kilianpaquier/go-builder-generator/testdata/pkg"
)

// BuiltinBuilder represents Builtin's builder.
type BuiltinBuilder struct {
	build pkg.Builtin
}

// NewBuiltinBuilder creates a new BuiltinBuilder.
func NewBuiltinBuilder() *BuiltinBuilder {
	return &BuiltinBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *BuiltinBuilder) Copy() *BuiltinBuilder {
	return &BuiltinBuilder{b.build}
}

// Build returns built Builtin.
func (b *BuiltinBuilder) Build() *pkg.Builtin {
	result := b.build
	return &result
}

// Any sets Builtin's Any.
func (b *BuiltinBuilder) Any(value any) *BuiltinBuilder {
	b.build.Any = value
	return b
}

// Bool sets Builtin's Bool.
func (b *BuiltinBuilder) Bool(value bool) *BuiltinBuilder {
	b.build.Bool = value
	return b
}

// Byte sets Builtin's Byte.
func (b *BuiltinBuilder) Byte(value byte) *BuiltinBuilder {
	b.build.Byte = value
	return b
}

// Bytes sets Builtin's Bytes.
func (b *BuiltinBuilder) Bytes(bytes []byte) *BuiltinBuilder {
	b.build.Bytes = bytes
	return b
}

// Complex128 sets Builtin's Complex128.
func (b *BuiltinBuilder) Complex128(value complex128) *BuiltinBuilder {
	b.build.Complex128 = value
	return b
}

// Complex64 sets Builtin's Complex64.
func (b *BuiltinBuilder) Complex64(value complex64) *BuiltinBuilder {
	b.build.Complex64 = value
	return b
}

// Error sets Builtin's Error.
func (b *BuiltinBuilder) Error(value error) *BuiltinBuilder {
	b.build.Error = value
	return b
}

// Float32 sets Builtin's Float32.
func (b *BuiltinBuilder) Float32(value float32) *BuiltinBuilder {
	b.build.Float32 = value
	return b
}

// Float64 sets Builtin's Float64.
func (b *BuiltinBuilder) Float64(value float64) *BuiltinBuilder {
	b.build.Float64 = value
	return b
}

// Int sets Builtin's Int.
func (b *BuiltinBuilder) Int(value int) *BuiltinBuilder {
	b.build.Int = value
	return b
}

// Int32 sets Builtin's Int32.
func (b *BuiltinBuilder) Int32(value int32) *BuiltinBuilder {
	b.build.Int32 = value
	return b
}

// Int64 sets Builtin's Int64.
func (b *BuiltinBuilder) Int64(value int64) *BuiltinBuilder {
	b.build.Int64 = value
	return b
}

// Int8 sets Builtin's Int8.
func (b *BuiltinBuilder) Int8(value int8) *BuiltinBuilder {
	b.build.Int8 = value
	return b
}

// Rune sets Builtin's Rune.
func (b *BuiltinBuilder) Rune(value rune) *BuiltinBuilder {
	b.build.Rune = value
	return b
}

// Runes sets Builtin's Runes.
func (b *BuiltinBuilder) Runes(runes []rune) *BuiltinBuilder {
	b.build.Runes = runes
	return b
}

// String sets Builtin's String.
func (b *BuiltinBuilder) String(value string) *BuiltinBuilder {
	b.build.String = value
	return b
}

// Uint sets Builtin's Uint.
func (b *BuiltinBuilder) Uint(value uint) *BuiltinBuilder {
	b.build.Uint = value
	return b
}

// Uint16 sets Builtin's Uint16.
func (b *BuiltinBuilder) Uint16(value uint16) *BuiltinBuilder {
	b.build.Uint16 = value
	return b
}

// Uint32 sets Builtin's Uint32.
func (b *BuiltinBuilder) Uint32(value uint32) *BuiltinBuilder {
	b.build.Uint32 = value
	return b
}

// Uint64 sets Builtin's Uint64.
func (b *BuiltinBuilder) Uint64(value uint64) *BuiltinBuilder {
	b.build.Uint64 = value
	return b
}

// Uint8 sets Builtin's Uint8.
func (b *BuiltinBuilder) Uint8(value uint8) *BuiltinBuilder {
	b.build.Uint8 = value
	return b
}

// Uintptr sets Builtin's Uintptr.
func (b *BuiltinBuilder) Uintptr(value uintptr) *BuiltinBuilder {
	b.build.Uintptr = value
	return b
}

// UnsafePointer sets Builtin's UnsafePointer.
func (b *BuiltinBuilder) UnsafePointer(unsafePointer unsafe.Pointer) *BuiltinBuilder {
	b.build.UnsafePointer = unsafePointer
	return b
}
