// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

// Code generated from types.go

package builders

import "github.com/kilianpaquier/go-builder-generator/root"

//go:generate go run github.com/kilianpaquier/go-builder-generator/cmd/go-builder-generator@latest generate -d . -f ../types.go -s RootType

// RootTypeBuilder represents RootType's builder.
type RootTypeBuilder struct {
	build root.RootType
}

// NewRootTypeBuilder creates a new RootTypeBuilder.
func NewRootTypeBuilder() *RootTypeBuilder {
	return &RootTypeBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *RootTypeBuilder) Copy() *RootTypeBuilder {
	return &RootTypeBuilder{b.build}
}

// Build returns built RootType.
func (b *RootTypeBuilder) Build() *root.RootType {
	result := b.build
	return &result
}

// Field sets RootType's Field.
func (b *RootTypeBuilder) Field(field int64) *RootTypeBuilder {
	b.build.Field = field
	return b
}
