// Code generated by go-builder-generator (https://github.com/kilianpaquier/go-builder-generator). DO NOT EDIT.

package builders

import (
	"github.com/kilianpaquier/go-builder-generator/testdata/success_generic_field"
)

// StructBuilder represents Struct's builder.
type StructBuilder struct {
	build success_generic_field.Struct
}

// NewStructBuilder creates a new StructBuilder.
func NewStructBuilder() *StructBuilder {
	return &StructBuilder{}
}

// Copy reassigns the builder struct (behind pointer) to a new pointer and returns it.
func (b *StructBuilder) Copy() *StructBuilder {
	return &StructBuilder{b.build}
}

// Build returns built Struct.
func (b *StructBuilder) Build() *success_generic_field.Struct {
	result := b.build
	return &result
}

// GenericField sets Struct's GenericField.
func (b *StructBuilder) GenericField(genericField success_generic_field.GenericType[int64]) *StructBuilder {
	b.build.GenericField = genericField
	return b
}

// GenericFields sets Struct's GenericFields.
func (b *StructBuilder) GenericFields(genericFields []*success_generic_field.GenericType[success_generic_field.GenericValue]) *StructBuilder {
	b.build.GenericFields = genericFields
	return b
}
